"""empty message

Revision ID: 358a5ce88983
Revises: fa14dd7b00c6
Create Date: 2018-08-09 10:05:57.522832

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '358a5ce88983'
down_revision = 'fa14dd7b00c6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('blog', sa.Column('content', sa.Text(), nullable=True))
    op.drop_column('blog', 'context')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('blog', sa.Column('context', mysql.TEXT(), nullable=True))
    op.drop_column('blog', 'content')
    # ### end Alembic commands ###
