"""empty message

Revision ID: 5f821ee6761e
Revises: 822ac3a5683d
Create Date: 2018-05-06 16:14:53.009212

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '5f821ee6761e'
down_revision = '822ac3a5683d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('roles', sa.String(length=80), nullable=True))
    op.drop_column('user', 'role')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('role', mysql.VARCHAR(length=80), nullable=True))
    op.drop_column('user', 'roles')
    # ### end Alembic commands ###
