"""empty message

Revision ID: 822ac3a5683d
Revises: 4f1a2d22f135
Create Date: 2018-05-06 16:14:32.331346

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '822ac3a5683d'
down_revision = '4f1a2d22f135'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user',
    sa.Column('id', sa.String(length=45), nullable=False),
    sa.Column('username', sa.String(length=255), nullable=True),
    sa.Column('password', sa.String(length=255), nullable=True),
    sa.Column('avatar', sa.String(length=255), nullable=True),
    sa.Column('role', sa.String(length=80), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('username')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user')
    # ### end Alembic commands ###
