"""empty message

Revision ID: fa14dd7b00c6
Revises: 73629c376b1d
Create Date: 2018-08-09 10:01:52.794587

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'fa14dd7b00c6'
down_revision = '73629c376b1d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('blog', 'author')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('blog', sa.Column('author', mysql.VARCHAR(length=255), nullable=True))
    # ### end Alembic commands ###
